/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package application;

import org.junit.jupiter.api.Test;

import Puzzle.App;


class AppTest {
    @Test void appHasAGreeting() {
    }
}
